=== TennesseeAlves/CabinetInfirmier/data/xsd/actes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:act="http://www.univ-grenoble-alpes.fr/l3miage/actes"
        targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/actes"
        elementFormDefault="qualified"
        >
    
    <!-- elem racine -->
    <element name="ngap" type="act:Ngap"/>
    
    <complexType name="Ngap">
        <sequence>
            <element name="types" type="act:Types"/>
            <element name="actes" type="act:Actes"/>
        </sequence>
    </complexType>


    <!-- Types -->
    <complexType name="Types">
        <sequence>
           <element name="type" type="act:Type" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <!-- Actes -->
    <complexType name="Actes">
        <sequence>
           <element name="acte" type="act:Acte" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <!-- Type -->
    <complexType name="Type">
        <simpleContent>
            <extension base="string">
                <attribute name="id" type="string"/>
            </extension>
        </simpleContent>
    </complexType>

    <!-- Acte -->
    <complexType name="Acte">
        <simpleContent>
            <extension base="string">
                <attribute name="id" type="int"/>
                <attribute name="type" type="string"/>
                <attribute name="clÃ©" type="act:typeCle"/>
                <attribute name="coef" type="float"/>
            </extension>
        </simpleContent>
    </complexType>

    <!-- Enumeration des types de cles -->
    <simpleType name="typeCle">
        <restriction base="string">
            <enumeration value="AMI"/>
            <enumeration value="AIS"/>
            <enumeration value="DI"/>
        </restriction>
    </simpleType>
    
    
</schema>

=== TennesseeAlves/CabinetInfirmier/data/xml/actes.xml
<?xml version="1.0" encoding="UTF-8"?>
<ngap
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.univ-grenoble-alpes.fr/l3miage/actes"
    xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/l3miage/actes ../xsd/actes.xsd"
>
    <types>
        <type id="pi">prélèvements et injections</type>
        <type id="pc">pansements courants</type>
        <type id="pl">
            pansements lourds et complexes nécessitant des condition
            d’asepsie rigoueuse
        </type>
        <type id="sd">
            Soins infirmiers à domicile pour un patient, quel que
            soit son âge, en situation de dépendance temporaire ou permanante.
        </type>
    </types>
    <actes>
        <acte id="101" type="pi" clé="AMI" coef="1.5">
            Prélèvement par ponction veineuse directe
        </acte>
        <acte id="102" type="pi" clé="AMI" coef="5">
            Saignée
        </acte>
        <acte id="103" type="pi" clé="AMI" coef="1">
            Prélèvement aseptique cutané ou de sécrétions muqueuses, prélè
            vement
            de selles ou d’urine pour examens sytologiques, bactériologiques,
            mycologiques.
        </acte>
        <!-- ... et plein d’autres actes-->
    </actes>
</ngap>
