=== TennesseeAlves/CabinetInfirmier/data/xsd/niveau.xsd
<?xml version="1.0"?>
<schema xmlns:niv="http://www.univ-grenoble-alpes.fr/niveau"
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.univ-grenoble-alpes.fr/niveau"
        elementFormDefault="qualified">

    <!-- Element racine -->
    <element name="niveau" type="niv:Niveau"/>

    <complexType name="Niveau">
        <sequence>
            <element name="tempsDeJeu" type="int"/>
            <element name="rangÃ©e" type="niv:LigneDeTables" minOccurs="2" maxOccurs="20"/>
        </sequence>
    </complexType>

    <complexType name="LigneDeTables">
        <sequence>
            <element name="table" type="niv:Trinaire" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <simpleType name="Trinaire">
        <restriction base="int">
            <enumeration value="0"/>
            <enumeration value="1"/>
            <enumeration value="2"/>
        </restriction>
    </simpleType>
</schema>

=== TennesseeAlves/CabinetInfirmier/data/xml/niveau.xml
<?xml version="1.0" encoding="utf-8"?>
<niveau xmlns="http://www.univ-grenoble-alpes.fr/niveau" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.univ-grenoble-alpes.fr/niveau ../xsd/Niveau.xsd">
    <tempsDeJeu>10</tempsDeJeu>
    <rangée>
        <table>0</table>
        <table>2</table>
        <table>1</table>
        <table>2</table>
    </rangée>
    <rangée>
        <table>0</table>
    </rangée>
    <rangée>
        <table>2</table>
        <table>0</table>
        <table>0</table>
        <table>1</table>
        <table>2</table>
        <table>1</table>
    </rangée>
    <rangée>
        <table>0</table>
        <table>0</table>
        <table>0</table>
        <table>0</table>
        <table>0</table>
        <table>0</table>
        <table>0</table>
        <table>1</table>
        <table>0</table>
    </rangée>
</niveau>
